# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Jonas A"
__copyright__ = "Copyright 2021, Jonas A"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/bcftools.smk"
include: "rules/bgzip_vcf.smk"
include: "rules/filter_vcf.smk"
include: "rules/sort_vcf.smk"
include: "rules/tabix_vcf.smk"
include: "rules/vep.smk"


report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),
