# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Jonas A"
__copyright__ = "Copyright 2021, Jonas A"
__email__ = "jonas.almlof@igp.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/filter_vcf_on_format.smk"
include: "rules/artifact_filter.smk"
include: "rules/background_filter.smk"


report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),
