$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  required:
    - samples
    - units
    - resources
    - default_container

  reference:
    artifacts:
      type: string
      description: file with artifact data used in artifact_filter
    background:
      type: string
      description: file with background level data used in background_filter
    required:
      - artifacts
      - background


  filter_vcf_on_format:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for filter_vcf_on_format
      container:
        type: string
        description: name or path to docker/singularity container
      filter:
        type: string
        description: filtering parameters to filter_vcf_on_format
      extra:
        type: string
        description: extra parameters to filter_vcf_on_format

  artifact_filter:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for artifact_filter
      container:
        type: string
        description: name or path to docker/singularity container

  background_filter:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for background_filter
      container:
        type: string
        description: name or path to docker/singularity container
      nr_min_sd:
        type: integer
        description: number of standard deviations from median to not get a filter flag
