$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  reference:
    fasta:
      type: string
      description: file with reference fasta file
    required:
      - fasta

  required:
    - default_container
    - resources
    - samples
    - units

  default_container:
    type: string
    description: name or path to a default docker/singularity container

  resources:
    type: string
    description: Path to resources.yaml file

  samples:
    type: string
    description: path to samples.tsv file

  units:
    type: string
    description: path to units.tsv file

  bcftools_filter_exclude_region:
    type: object
    description: parameters for bcftools filter
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      TAG_NAME:
        type: string
        description: |
          the key TAG_NAME must be the same as the wildcard {tag}, found in the output file path. We can have multiple different TAG_NAME where each TAG_NAME points to a bed file used to
          exclude regions. INDELs are excluded based on start position.
      extra:
        type: string
        description: extra parameters applied to all TAG_NAME files

  bcftools_filter_include_region:
    type: object
    description: parameters for bcftools filter
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      TAG_NAME:
        type: string
        description: | 
          the key TAG_NAME must be the same as the wildcard {tag}, found in the output file path. We can have multiple different TAG_NAME where each TAG_NAME points to a bed file used to exclude
          regions. INDELs are excluded based on start position. Overlapping regions lead to duplicated variants.
      extra:
        type: string
        description: extra parameters applied to all TAG_NAME files

  bcftools_view:
    type: object
    description: parameters for bcftools view
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      TAG_NAME:
        type: string
        description: |
          the key TAG_NAME must be the same as the wildcard {tag}, found in the output file path. We can have multiple different TAG_NAME where each TAG_NAME define settings 
          (e.g --apply-filter PASS or -M2 -m2 -v snps) that will be forwarded to bcftools view.
      extra:
        type: string
        description: extra parameters that will be added to all TAG_NAME settings

  filter_vcf:
    type: object
    description: parameters for filter vcf
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      TAG_NAME:
        type: string
        description: | 
          the key TAG_NAME must be the same as the wildcard {tag}, found in the output file path. We can have multiple different TAG_NAME where each TAG_NAME points to 
          a yaml file with filter settings
        description: Config file specifying which filters should be applied.
      sample_name_regex:
        type: string
        description: Regex used to match which sample column that will be used for filtering.
