$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container

  required:
    - samples
    - units
    - resources
    - default_container

  reference:
    fasta:
      type: string
      description: file with reference fasta file
    artifacts:
      type: string
      description: file with artifact data used in artifact_filter
    background:
      type: string
      description: file with background level data used in background_filter
    required:
      - fasta
      - artifacts
      - background

  bcftools_filter_exclude_region:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for bcftools_filter_exclude_region
      container:
        type: string
        description: name or path to docker/singularity container
      filter:
        type: string
        description: Exclude variants in vcf file based on regions in bed file. INDELs are exluded based on start position.
      extra:
        type: string
        description: extra parameters to bcftools_filter_exclude_region

  bcftools_filter_include_region:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for bcftools_filter_include_region
      container:
        type: string
        description: name or path to docker/singularity container
      filter:
        type: string
        description: Include variants in vcf file based on regions in bed file. Overlapping regions lead to duplicated variants.
      extra:
        type: string
        description: extra parameters to bcftools_filter_include_region

  hard_filter:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for hard_filter
      container:
        type: string
        description: name or path to docker/singularity container
      filter_config:
        type: string
        description: Config file specifying which hard filters should be applied.

  soft_filter:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for soft_filter
      container:
        type: string
        description: name or path to docker/singularity container
      filter_config:
        type: string
        description: Config file specifying which soft filters should be applied.

  sort_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for sort_vcf
      container:
        type: string
        description: name or path to docker/singularity container
