resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.0"

reference:
  fasta: "reference/HES45.fna"
  artifacts: "reference/artifact_positions_chr1.txt"
  background: "reference/background_panel_HES45.tsv"
  design_bed: "reference/twist_DNA_solid.HES45.annotated.bed"

bcftools_filter_include_region:
  noexon1: "reference/twist_DNA_solid.HES45.annotated.noexon1.bed"

bcftools_filter_exclude_region:
  noexon1: "reference/twist_DNA_solid.HES45.annotated.noexon1.bed"
