resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/HES45.fna"
  artifacts: "reference/artifact_positions_chr1.txt"
  background: "reference/background_panel_HES45.tsv"

bgzip_vcf:
  container: "docker://hydragenetics/common:0.0.1"

tabix_vcf:
  container: "docker://hydragenetics/common:0.0.1"

add_multi_snv_in_codon:
  container: "docker://hydragenetics/common:0.0.1"

background_filter:
  container: "docker://hydragenetics/common:0.0.1"

sort_vcf:
  container: "docker://hydragenetics/common:0.0.1"

artifact_filter:
  container: "docker://hydragenetics/common:0.0.1"
