resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

filter_vcf_on_format:
  container: "docker://hydragenetics/common:0.0.1"

artifact_filter:
  artifacts: "reference/artifact_positions_chr1.txt"

background_filter:
  background: "reference/background_panel_HES45.tsv"
