resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

filter_vcf_on_format:
  container: "docker://gmsuppsala/somatic:develop"
